repos:
  - repo: https://github.com/psf/black
    rev: master
    hooks:
      - id: black
        name: black
        language: system
        entry: black
        require_serial: true
        types: [python]

default_language_version:
  python: python3
